Repository tsirysndr/envhub, pull requests merged in 2023-10, with the labels that each got.

#4 feat: add envhub banner and update readme
  README.md
  banner.png
Labels: documentation

#5 feat: add support for GNU Stow as a symlink manager
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/cmd/unuse.rs
  crates/cli/src/cmd/use.rs
  crates/hm/src/switch.rs
  crates/stow/Cargo.toml
  crates/stow/src/install.rs
  crates/stow/src/lib.rs
  crates/stow/src/stow.rs
  crates/stow/src/unstow.rs
Labels: enhancement

#6 feat: add support for pkgx, homebrew and devbox as package manager
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/cmd/use.rs
  crates/cli/src/helpers.rs
  crates/hm/src/switch.rs
  crates/pkgs/src/homebrew.rs
  examples/brew/dotfiles/.screenrc
  examples/brew/envhub.hcl
  examples/devbox/dotfiles/.screenrc
  examples/devbox/envhub.hcl
  examples/pkgx/dotfiles/.screenrc
  examples/pkgx/envhub.hcl
Labels: enhancement

#7 fix(pkgx): allow specify 'org' in package name
  crates/pkgs/src/pkgx.rs
  examples/pkgx/envhub.hcl
Labels: bug

#8 feat: add packages sub-commands
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/cmd/package.rs
  crates/cli/src/cmd/use.rs
  crates/cli/src/helpers.rs
  crates/cli/src/main.rs
  crates/pkgs/src/pkgx.rs
  crates/providers/src/github.rs
  crates/providers/src/lib.rs
  crates/providers/src/local.rs
  crates/providers/src/s3.rs
  examples/pkgx/envhub.hcl
Labels: enhancement

#9 feat: add env subcommands
  crates/cli/src/cmd/env.rs
  crates/cli/src/cmd/package.rs
Labels: enhancement

#10 feat: add file subcommands
  crates/cli/src/cmd/file.rs
  crates/cli/src/cmd/unuse.rs
  crates/cli/src/main.rs
Labels: enhancement

#11 feat: add `status` subcommand
  crates/cli/src/cmd/mod.rs
  crates/cli/src/cmd/status.rs
  crates/cli/src/cmd/unuse.rs
  crates/cli/src/cmd/use.rs
  crates/cli/src/main.rs
Labels: enhancement

#14 feat: run `pkgx git` instead of `git`
  Cargo.lock
  crates/cli/src/helpers.rs
  crates/providers/Cargo.toml
  crates/providers/src/github.rs
Labels: enhancement

#16 feat(github): load specific git branch
  crates/cli/src/cmd/status.rs
  crates/cli/src/cmd/use.rs
  crates/cli/src/helpers.rs
  crates/providers/src/github.rs
Labels: enhancement

#19 fix(gh): use `gh repo clone` instead of `git clone`
  crates/providers/src/github.rs
Labels: bug

#21 fix(unuse): resolve bug on unuse environment
  crates/cli/src/cmd/unuse.rs
Labels: bug

#22 allow using multiple packages manager at same time
  crates/cli/src/cmd/use.rs
  crates/cli/src/helpers.rs
  crates/providers/src/local.rs
Labels: enhancement
